theme = "catppuccin_latte"

[editor]
end-of-line-diagnostics = "hint"
bufferline="always"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
color-modes = true
cursorline = true
lsp.display-inlay-hints = true

[editor.statusline]
right = ["diagnostics", "primary-selection-length", "selections", "position", "file-encoding"]
left = ["mode", "spacer", "diagnostics", "workspace-diagnostics", "spinner", "spacer", "file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.inline-diagnostics]
cursor-line = "error"
# cursor-line = "hint"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
# j = { k = "normal_mode"}

[keys.normal]
ret = ["save_selection", "goto_word"] # Go to definition in next view (split windows)
A-s = "save_selection"
C-s = ":write"
C-y = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open"

# Editor navigation
C-h = "jump_view_left"
C-H = "swap_view_left"
C-l= "jump_view_right"
C-L= "swap_view_right"

# Buffer navigation
S-l = "goto_next_buffer"
S-h = "goto_previous_buffer"

# Buffer management
C-b = { o= ":buffer-close-others" }

[keys.normal.space]
q = ":quit"
