theme = "tokyonight_day"

[editor]
end-of-line-diagnostics = "hint"
bufferline="always"
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
color-modes = true

[editor.statusline]
right = ["diagnostics", "primary-selection-length", "selections", "position", "file-encoding"]
left = ["mode", "spacer", "diagnostics", "workspace-diagnostics", "spinner", "spacer", "file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.inline-diagnostics]
cursor-line = "error"

[keys.normal]
ret = ["save_selection", "goto_word"] # Go to definition in next view (split windows)
